version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: postgres@888
    ports: 
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  express:
    build:
      context: .
    environment:
      DB_SCHEMA: share_pg
      DB_USER: db_admin
      DB_PASSWORD: postgres@888
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
